blog/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views
from django.views.decorators.csrf import csrf_exempt
app_name = 'blog'

urlpatterns = [
    # path('', TemplateView.asview(template_name="blog/index.html")),
    #path('', TemplateView.as_view(template_name="blog/index.html"),name="home"),
    path('', views.postlist, name='home'),
    path("api-profile/<id>",views.handleApiProfile,name="handleApiProfile"),
    path("api-update-profile",csrf_exempt(views.apiUpdateProfile),name="apiUpdateProfile"),
    path("api-update-password",csrf_exempt(views.handleApiChangePassword),name="handleApiChangePassword"),
    path("api-add-blogs",csrf_exempt(views.addApiBlogPage),name="addApiBlogPage"),
    path("api-update-blogs",csrf_exempt(views.editApiBlogPage),name="editApiBlogPage"),
    path("api-delete-blogs/<id>",views.deleteApiBlogPage,name="deleteApiBlogPage"),
    path("api-manage-blogs/<id>",views.handleApiManageBlogs,name="handleApiManageBlogs"),
    path("api-single-blog/<id>",views.handleApiSingleManageBlogs,name="handleApiSingleManageBlogs"),
    path("login/", views.login_request, name="login"),
    path("sidebar/", views.sidebar, name="sidebar"),
    path("profile/", views.profilePage, name="profile"),
    path("change-password/", views.changePasswordPage, name="change-password"),
    path("manage-blogs/", views.myBlogPage, name="manage-blogs"),
    path("manage-blogs/add", views.addBlogPage, name="add-manage-blogs"),
    path("manage-blogs/edit/<id>", views.editBlogPage, name="edit-manage-blogs"),
    path("manage-blogs/delete/<id>", views.deleteBlogPage, name="delete-manage-blogs"),
    path("api-login", views.api_login_request, name="api_login_request"),
    path("api-register", views.api_register_request, name="api_register_request"),
    path('about',views.about, name= 'about'),
    path('policy',views.policy, name= 'policy'),
    path('contact',views.contact, name= 'contact'),
    path('map',views.map, name= 'map'),
    path('cdc',views.cdc, name= 'cdc'),
    path('nearest/',views.nearest_of_you, name= 'nearest'),
    path('google_api',views.google_api_callig, name= 'google_api_callig'),
    path('<slug:slug>/', views.postDetail, name='post_detail'),
    path("register", views.registration, name="register"),
    path("logout", views.logout_request, name= "logout"),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    # entry point to blog api
    path('api/', include('blog_api.urls', namespace='blog_api')),
    path('', include("blog.urls", namespace='blog')),
    


]
if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

blog/models.py
from django.db import models
# post assciated with user
from django.contrib.auth.models import User
# timestamp post
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.CharField(max_length=100,default="0")
    
    #default string rep that idenditfies item  shown in datatbase which is name
    def  __str__(self):
        return self.name



class Post(models.Model):

    #post objects custom model manager that by default returns data from database and outputs data
    # default instead of running objects all on data when making a query can run  post objects which will  filter and  get
    #published posts
    # if post flagged as published will return published post
    class PostObjects(models.Manager):
        def get_queryset(self) :
            return super().get_queryset().filter(status="published")

    options = (
        ('draft', 'Draft'),
        ('published', "Published"),
        ('pending', "Pending"),
    )

    #usually if delete category delete all posts in category but with .Protect
    # .Protect/if delete category it has no effect on the post
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, default=1)
    title = models.CharField(max_length = 250)
    excerpt = models.TextField(null=True)   
    content = models.TextField()
    #slug is url can be used to slugify the title to identify each post /used in lieu of id to collect data
    slug = models.SlugField(max_length=250, unique_for_date='published')
    #Image 
    image = models.ImageField(blank = True)
    #fire off each time a post is created/timezone
    published = models.DateTimeField(default=timezone.now)

    #if user made a new post then user connected to post
    #CASCADE means if user deleted a post  is deleted
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    status = models.CharField(
        max_length=10,  choices=options,  default='published')
    objects = models.Manager() #default manager
    postobjects = PostObjects()  #custom manager

    #display data in ascending/descending order by published 
    class Meta:
        ordering = ('-published' ,)
        #returns title by defualt for any data returned
        def __str__(self):
            return self.title    

class Maps(models.Model):
    travel_advisory = models.CharField(max_length=255)
    advisory_level = models.CharField(max_length=255)
    date = models.DateTimeField(default=timezone.now)
    latitute = models.CharField(max_length=50)
    location_name = models.CharField(max_length=255,default="")
    longtittude  = models.CharField(max_length=50)

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

blog/views.py
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render,redirect
import requests
from .models import Post,Maps
from django.views import generic
import json
from .forms import NewUserForm
from django.contrib.auth import login,logout,authenticate
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage

# django home page function
def blogList(request):
    context = {}
    posts = requests.get('http://127.0.0.1:8000/api?format=json')
    context['posts'] = posts.json()
    return render(request,'blog/index.html',context)

# from django.views import generic
# from .models import Post
# class PostList(generic.ListView):
#     queryset = Post.objects.all()
#     template_name = 'blog/index.html'

# rendering data of postlist of all blogs
# displays all of post
def postlist(request):
    post = Post.objects.all()
    context = {
        "post_list":post

    }
    # home url
    return render(request,'blog/index.html',context)

# class PostDetail(generic.DetailView):

#     model = Post
#     template_name = 'blog/post_detail.html'

# post detail from blog model/click on read more button
# read data from the databse, filter, and order it
def postDetail(request,slug):
    post = Post.objects.get(id=slug)
    print(post)
    context = {
        "post": post
    }
    # post detail url
    return render(request,'blog/post_detail.html', context)

def about(request):
    return render(request,"blog/about.html",{})

def policy(request):
    return render(request,"blog/policy.html",{})

def contact(request):
    return render(request,"blog/contact.html",{})

def cdc(request):
    return render(request,"blog/cdc.html",{})

def sidebar(request):
    return render(request,"blog/sidebar.html",{})
    
def map(request):
    return render(request,"blog/map.html",{})

# def map(request):
#     mapsData = []
#     mapObject = Maps.objects.all()
#     for obj in mapObject:
#         mapsData.append([obj.travel_advisory,obj.advisory_level,obj.latitute,obj.longtittude,obj.location_name])
#     context = {}
#     context['mapsData'] = json.dumps(mapsData)
#     return render(request,"blog/map.html",context)

# django nearest
def nearest_of_you(request):
    context={}
    context['places'] = {}
    #check for form submission with post aand then code will execute
    if request.method == 'POST':
        api_key = 'AIzaSyAInX0_Rk6nMsqubmBSAxqrm1BjemVP47E'
        url = "https://maps.googleapis.com/maps/api/place/textsearch/json?key="+api_key+"&"
        url += 'type='+request.POST.get('type')+"&"
        url += 'radius='+request.POST.get('radius')+"&"
        url += 'location='+request.POST.get('location')+"&"
        url += 'query='+request.POST.get('keyword') 
        r = requests.get(url)
        result = r.json() 
        y = result['results']
        for i in range(len(y)):
            context['places'][y[i]['name']] = y[i]['name']
            print(context['places']) 
    return render(request,'blog/nearest.html',context) 
# api nearest search for react
def google_api_callig(request):
    # AIzaSyAInX0_Rk6nMsqubmBSAxqrm1BjemVP47E

    # AIzaSyD4GC-KQEnuxWa-QszhV5h4-4dodTG5nWg
        api_key = 'AIzaSyAInX0_Rk6nMsqubmBSAxqrm1BjemVP47E'
        url = "https://maps.googleapis.com/maps/api/place/textsearch/json?key="+api_key+"&"
        url += 'type='+request.GET.get('type')+"&"
        url += 'radius='+request.GET.get('radius')+"&"
        url += 'location='+request.GET.get('location')+"&"
        url += 'query='+request.GET.get('keyword')
        # get method of request module
        # return response object
        r = requests.get(url)
        # json method of response object convert
        #  json format data into python format data
        result = r.json() 
        print(result)
        return JsonResponse(result)

# django registration
def registration(request):
    context = {}
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            return redirect("/")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    # forms.py
    context['register_form'] = form
    return render(request,'blog/register.html',context)

# register new user in react/api react
def api_register_request(request):
    response = {"status":0}
    # passed variables in register.js of username(u), email(e), password(p)
    uname = request.GET.get("u")
    email=request.GET.get("e")
    passwd = request.GET.get("p")
    if User.objects.filter(username=uname).exists():
        return JsonResponse(response)
    if User.objects.filter(email=email).exists():
        return JsonResponse(response) 
    user = User.objects.create_user(username=uname,email=email,password=passwd)
    response ={"status":1}
    return JsonResponse(response)
    
# django logout
def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.") 
    return redirect("/login")

# django login page
def login_request(request):
    if request.user.is_authenticated:
        return redirect("/")
    context = {}
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            # clearing the data for html page//clean data<t>USername</t>
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("/")
            else:
                messages.warning(request,"Invalid username or password.")
        else:
            messages.warning(request,"Invalid username or password.")
    form = AuthenticationForm()
    context['login_form'] = form
    return render(request,'blog/login.html',context)

# django api for react for login
def api_login_request(request):
    # if response is 0/false username and password is incorrect
    #returns a response of 0
    response = {"status":0}
    username = request.GET.get("username")
    password = request.GET.get("password")
    # print(username)
    # print(password)
    # if username and password is correct rtns response1/true 
    # 
    user = authenticate(username=username,password=password)
    if user is not None:
        #  if response status is 1 successful login and return user id
        # refers to local storage in login.js for user id
        response = {"status":1,"id":user.id}
    return JsonResponse(response)
    
# update profile page in django/Your Profile section
def profilePage(request):
    if request.user.is_authenticated == False:
        return redirect("/login")
    context = {}
    print(request.user.id)
    if request.method == "POST":
        user = User.objects.get(pk=request.user.id)
        user.first_name = request.POST.get('name')
        user.last_name = request.POST.get("lastname")
        user.email = request.POST.get("email")
        user.save()
        messages.success(request,"Successfully updated profile information")
        return redirect("/profile")
    return render(request,"blog/profile.html",context)    

# django change password in profile
def changePasswordPage(request):
    if request.user.is_authenticated == False:
        return redirect("/login")   
    context = {}
    if request.method == "POST":
        passwd = request.POST.get("password")
        cpasswd = request.POST.get("cpassword")
        if passwd != cpasswd:
            messages.warning(request,"Password should be same!")
            return redirect("/change-password")
        user = User.objects.get(pk=request.user.id)
        user.set_password(passwd)
        user.save()
        messages.success(request,"Successfully updated password")
        return redirect("/change-password")
    return render(request,"blog/changepassword.html",context)    

# My Blog Secton
def myBlogPage(request):
    if request.user.is_authenticated == False:
        return redirect("/login") 
    context = {}
    # gets current user  that is logged in
    user = User.objects.get(pk=request.user.id)
    # get blog created by current user  an
    context['blogs'] = Post.objects.filter(author=user).all()
    return render(request,"blog/manage-blog.html",context) 

# django addnew blog
def addBlogPage(request):
    if request.user.is_authenticated == False:
        return redirect("/login") 
    # after submit button is clicked lines 215-223 will activate
    if request.method == "POST":
        data = request.POST
        # myfile returns all data of image
        myfile = request.FILES['file']
        # then call django method FileSystemStorage() to upload files
        fs = FileSystemStorage()
        # saved fs file in fileName by calling fs.save method//name is the name picture displayed on blog output
        fileName = fs.save(myfile.name,myfile)
        # created a new blog using Post.objects and passing all parameters
        Post.objects.create(title=data.get("title"),content=data.get("content"),excerpt=data.get("excerpt"),author=request.user,image=fileName)
        messages.success(request,"Successfully created a new blog")
        return redirect("/manage-blogs")
    context = {}
    # rendering the new blog form
    return render(request,"blog/add-blog.html",context) 

# edit blog page in django
def editBlogPage(request,id):
    # if user not logged in/authenticated rediret login page
    if request.user.is_authenticated == False:
        return redirect("/login")
    if request.method == "POST":
        data = request.POST

blog/templates/blog/about 2.html
{% extends 'blog/base.html' %} {% block content %}

<h5>This is our about us page</h5>


{% endblock %}

blog/templates/blog/about 3.html
{% extends 'blog/base.html' %} {% block content %}

<h5>This is our about us page</h5>

{% endblock %}

blog/templates/blog/base 2.html
<!DOCTYPE html>
<html>

    <head>
        <title>Django Central</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">Django central</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'blog:about' %}">About</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'blog:policy' %}">Policy</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'blog:contact' %}">Contact</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'blog:cdc' %}">CDC</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'blog:sidebar' %}">Sidebar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    
        <!-- Footer -->
        <footer class="py-3 bg-grey">
            <p class="m-0 text-dark text-center ">Copyright &copy; Django Central</p>
        </footer>
    </body>
</html>

blog/templates/blog/base 3.html
<!DOCTYPE html>
<html>

    <head>
        <title>Django Central</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">Django central</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'blog:about' %}">About</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'blog:policy' %}">Policy</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'blog:contact' %}">Contact</a>
                        </li>
                    </li>
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="{% url 'blog:cdc' %}">CDC</a>
                    </li>
                    <li class="nav-item text-black">
                        <a class="nav-link text-black font-weight-bold" href="{% url 'blog:sidebar' %}">Sidebar</a>
                    </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    
        <!-- Footer -->
        <footer class="py-3 bg-grey">
            <p class="m-0 text-dark text-center ">Copyright &copy; Django Central</p>
        </footer>
    </body>
</html>

blog/templates/blog/contact 3.html
{% extends 'blog/base.html' %} {% block content %}

<h5>This is our contact page</h5>

{% endblock %}

blog/templates/blog/contact.html
{% extends 'blog/base.html' %} {% block content %}
<div class="container">
<form>
    <div class="form-group">
        <label for="name">Name</label>
        <input type="name" class="form-control" id="name" placeholder="name">
      </div>
    <div class="form-group">
      <label for="exampleInputEmail1">Email address</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
      <label for="subject">Subject</label>
      <input type="subject" class="form-control" id="subject" placeholder="subject">
    </div>
    <div class="form-group">
        <label for="message">Message</label>
        <input type="message" class="form-control" id="message" placeholder="message">
      </div>
    <div>
    <!-- <button type="submit" class="btn btn-primary">Send Email</button> -->
    <a href="https://www.google.com/" class="btn btn-info" role="button">Submit</a>
  
    </div>

  </form>
</div>



{% endblock %}

blog/templates/blog/edit-blog.html
{% extends 'blog/base.html' %} {% block content %}
<div class="container profilePage">
	<div class="row">
		<div class="col-md-3 ">
		<div class="list-group ">
            <a href="/profile" class="list-group-item list-group-item-action">  Profile</a>
            <a href="/change-password" class="list-group-item list-group-item-action">Change Password</a>
            <a href="/manage-blogs" class="list-group-item list-group-item-action active">Blogs</a>
            <a href="/logout" class="list-group-item list-group-item-action">Logout</a>
        </div> 
		</div>
		<div class="col-md-9">
		    <div class="card">
		        <div class="card-body">
		            <div class="row">
		                <div class="col-md-12">
		                    <h4>Edit Blog</h4>
		                    <hr>
		                </div>
		            </div>
		            <div class="row">
		                <div class="col-md-12">
		                    <form method="post" enctype="multipart/form-data">
                              <div class="form-group row">
                                <label for="name" class="col-4 col-form-label">Title</label> 
                                <div class="col-8">
                                  <input  name="title"  class="form-control here" type="text" value="{{blog.title}}">
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="lastname" class="col-4 col-form-label">Excerpt</label> 
                                <div class="col-8">
                                  <textarea name="excerpt" class="form-control here">{{blog.excerpt}}</textarea>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="lastname" class="col-4 col-form-label">Content</label> 
                                <div class="col-8">
                                  <textarea name="content" class="form-control here">{{blog.content}}</textarea>
                                </div>
                              </div>
                              <div class="form-group row">
                                <label for="name" class="col-4 col-form-label">Image</label> 
                                <div class="col-8">
                                  <input id="name" name="file"  class="form-control here" type="file">
                                  <!-- if image is uploaded for the blog then image shown -->
                                  {% if blog.image != "" %}
                                    <img src ="/media/{{blog.image}}" style="width:100px;height:100px"/>
                                  {% endif %}
                                    {% csrf_token %}
                                </div>
                              </div>

                                <div class="form-group row">
                                <div class="offset-4 col-8">
                                  <button name="submit" type="submit" class="btn btn-primary">Update</button>
                                </div>
                              </div>
                            </form>
		                </div>
		            </div>
		            
		        </div>
		    </div>
		</div>
	</div>
</div>
{% endblock %}

blog/templates/blog/index 3.html
{% extends "blog/base.html" %} 
{% load static %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: white;
    }
    
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
    .img-responsive{max-width: 100%;}
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                    <p class="text-light">We Love Django As much as you do..! &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <img src="/media/{{post.image}}" class="img-responsive"/>
                        </div>
                        <div class="col-md-8">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="/{{ post.slug }}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
{%endblock%}

blog/templates/blog/index.html
{% extends "blog/base.html" %} 
{% load static %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: white;
    }
    
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
    .img-responsive{max-width: 100%;}
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                    <p class="text-light">We Love Django As much as you do..! &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <img src="/media/{{post.image}}" class="img-responsive"/>
                        </div>
                        <div class="col-md-8">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="/{{post.id }}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
{%endblock%}